import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/themeProvider";
import { Toaster } from "@/components/ui/toaster";
import { ChatProvider } from "@/components/providers/chatProvider";
import { SoundProvider } from "@/components/providers/soundProvider";
import { InputProvider } from "@/components/providers/inputProvider";

export const metadata: Metadata = {
  title: "Firechat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <ChatProvider>
            <SoundProvider>
              <InputProvider>{children}</InputProvider>
            </SoundProvider>
          </ChatProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
